import { getServerSession } from "next-auth"
import { options } from "./auth/[...nextauth]/options";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

	const session = await getServerSession(options);
	console.log("session: " + session?.user?.name);
  return (
		<div className="max-w-6xl m-auto">
			<div>{children}</div>
		</div>
  )
}
