import Nav from "@/components/Nav"
import SideNav from "@/components/appointments/SideNav"
import { ClerkProvider } from "@clerk/nextjs"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<ClerkProvider >
			<Nav />
			<div className="flex gap-8 max-w-6xl m-auto">
				<SideNav />
		      <div>{children}</div>
			</div>
		</ClerkProvider>
  )
}
