import { Metadata } from 'next/types'
import './globals.css'
import { Poppins } from 'next/font/google'
import Nav from '@/components/Nav'

const inter = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html lang="en">
			<body className={`${inter.className} bg-background`}>
			<Nav />
				<div className='m-auto '>
					{children}
				</div>
			</body>
		</html>
  )
}
